version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: notes-nginx
    working_dir: /var/www/html
    build:
      context: ./docker/nginx/
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./docker/nginx/startup.sh:/docker-entrypoint.d/startup.sh
      - ./:/var/www/html
    environment:
      - NGINX_HOST=lumen.notes.com
      - NGINX_PORT=80
    networks:
      - notes_default_network

#  php-fpm:
#    image: php:fpm
#    container_name: notes-php
#    working_dir: /var/www/html
#    ports:
#      - "8082:8099"
#    volumes:
#      - ./:/var/www/html
#      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
#      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
#      - ./docker/php/conf/php-fpm.conf:/usr/local/etc/php/conf.d/php-fpm.conf
#    build:
#      context: ./docker/php/

  postgres:
    container_name: notes-postgres
    image: postgres
    environment:
      - POSTGRES_DB=notes-db
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5433:5432"
    networks:
      - notes_default_network

  redis:
    image: redis
    container_name: notes-redis
    ports:
      - "6380:6379"
    networks:
      - notes_default_network

networks:
  notes_default_network:
    name: notes_default_network
