<?php

namespace Tests;

use App\Models\User;
use App\Services\Common\AuthService;
use Illuminate\Support\Facades\Cache;
use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use DatabaseMigrations;
//    static $migrationRun = false;

    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }

    protected function createAuthenticatedUser()
    {
        /** @var AuthService $authService */
        $authService = app(AuthService::class);
        $user = User::factory()->createOne();

        $tokens = $authService->signin($user->email, 'admin123');

        Cache::store('redis')->set('test.refreshToken', $tokens['refresh'], 30);
        Cache::store('redis')->set('test.accessToken', $tokens['access'], 30);

        return $user;
    }

    protected function getAccessToken()
    {
        return Cache::store('redis')->get('test.accessToken');
    }

    protected function getRefreshToken()
    {
        return Cache::store('redis')->get('test.refreshToken');
    }

//    protected function setUp(): void
//    {
//        parent::setUp(); // TODO: Change the autogenerated stub
//
//        /** Run migrations once */
//        if (!static::$migrationRun) {
//            $this->artisan('migrate:fresh');
//            static::$migrationRun = true;
//        }
//    }
}
