<?php

namespace Tests;

use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    static $migrationRun = false;

    /**
     * Creates the application.
     *
     * @return \Laravel\Lumen\Application
     */
    public function createApplication()
    {
        return require __DIR__.'/../bootstrap/app.php';
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        /** Run migrations once */
        if (!static::$migrationRun) {
            $this->artisan('migrate:fresh');
            static::$migrationRun = true;
        }
    }
}
